version: '3.8'

services:
  app:
    build: .
    ports:
      - "80:80"
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
    volumes:
      - ./logs:/var/www/html/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  app-dev:
    build: .
    ports:
      - "8080:80"
    environment:
      - APP_ENV=development
      - APP_DEBUG=true
    volumes:
      - ./src:/var/www/html/src
      - ./config:/var/www/html/config
      - ./public:/var/www/html/public
      - ./composer.json:/var/www/html/composer.json
      - ./logs:/var/www/html/logs
    command: >
      sh -c "composer install &&
             php-fpm &
             nginx -g 'daemon off;'" 