version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - FLASK_ENV=production
      - PORT=3000
      - SECRET_KEY=your-secret-key-here
    healthcheck:
      test: ["CMD", "python", "healthcheck.py"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  app-dev:
    build: .
    ports:
      - "3001:3000"
    environment:
      - FLASK_ENV=development
      - PORT=3000
      - SECRET_KEY=dev-secret-key
    volumes:
      - ./src:/app/src
      - ./requirements.txt:/app/requirements.txt
    command: python -m flask run --host=0.0.0.0 --port=3000 